# Configuração para encontrar as funções do Node.js corretamente
[functions]
  node_bundler = "esbuild"

# Configuração para a função agendada que roda a cada minuto
[functions.cron]
  schedule = "* * * * *"
